language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

before_install:
  - gem install bundler --version 1.15.4
  - bundle install

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile

env:
  - DB=postgresql

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare

matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5_1.gemfile
