language: ruby

rvm:
  - 2.2.4

before_install:
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.2.4@global bundler
  - gem install bundler --version 1.13.6
  - bundle install

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails5

env:
  - DB=postgresql

before_script:
  - rake app:db:create
  - rake app:db:migrate
  - rake app:db:test:prepare

